# Generated by Django 6.1 on 2026-08-12 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='full_text',
            field=models.TextField(blank=True, help_text="Paste the full story here so 'Listen to Story' narrates the entire book, not just the description."),
        ),
    ]
